---
title: "JSM2025参加記"
date: 2025-08-10
categories: ["学会参加記"]
---


アメリカのナッシュビルで開催された[Joint Statistical Meeting 2025](https://ww2.amstat.org/meetings/jsm/2025/conferenceinfo.cfm) (JSM2025) に参加した。初めての海外での国際学会で苦労も多かったが、得られたものは大きかった。


## 発表

Integrate Meta-analysis into Specific Study for Estimating Conditional Average Treatment Effectというタイトルでポスター発表した。セッションはBiostatisticsにするかEpidemiologyにするかで悩んだが、Epidemiologyにしてみた。いずれのセッションも日中に開催され、そこそこの人数が参加していた。誰も来ないことも危惧していたが、結果的には暇な時間は少なく、近い領域の研究者とディスカッションできてとても楽しい時間だった。


### 発表形式についての感想

口頭、ポスター、e-ポスターから発表形式が選べたが、今回はポスターで良かったと思う。口頭は15分~25分の発表で、参加者は多いがあまり質疑の時間がなかった。オーガナイザーが質疑の時間を取らないセッションもまあまああった。話したい場合は、終了後に話しかける必要があり、知り合いと雑談していたりもするので、若干ハードルが高い。

ポスターは割と博士学生やポスドクくらいの方の発表が多かった気がする。ポスター前でちゃんと準備している発表者はディスカッションする気満々で、アドバイスを求めてくる人も結構いた。ポスターを貼っていなくなる人もいたので、割と人次第っぽい。

e-ポスターはポスター発表に加えて、5分間の口頭発表 (ライトニングトーク) がある発表形式。ライトニングトークは聞きに行けなかったが、過去にe-ポスターで発表した方は満足度が高かったと言っていた。


## セッションについて

日本の統計関連学会連合大会に近いが、より幅広い雰囲気を感じた。修士や博士でこの学会に参加できる人は羨ましい。上述のような発表を聞けるセッションの他に、有名な研究者が1,2時間話すセッションや、他の研究者との交流を目的としたMixerなども企画されており、発表はハードルはあるけど試しに行ってみたいという人も楽しめるようになっていた。実際、アメリカ在住なら毎年行くだろうなという気がしている。

特に、ASAやRSSが主催しているセッションではJASAやJRSSBの論文の中からinviteされた発表をしており、最近の話題を紹介してくれるのでかなり面白かった。

あまりにも規模が大きいので見たいセッションの時間が被りまくるのは残念だったが、ちゃんと見たい発表を事前に整理して計画的に発表を聞けると良いだろう。


## 行くべきか？

研究を続けていくつもりの身としては、早いうちにトップレベルの研究者の発表を聞くべきだろうという気持ちで今回JSM2025に参加した。
日本国内にも素晴らしい研究をしている研究者がたくさんいるが、やはりキャリアの初期に1度は国際会議に行くべきだという気持ちは強くなった。

特にJSMは若手の研究者も多く、海外の知り合いができるというのも大きな利点になり得る。自身の発表に対して多様な意見をもらい得るという点も良い。
個人的にも、今後も行きたい学会の1つになった。本当に多くの研究者が発表するので、刺激が大きい。



## 初アメリカの感想


### 移動について

正直、ホテルや飛行機の予約や道中の移動をすべて1人でやろうとしたのは失敗だった。誰か頼れる人がいるなら必ずどうするのが良いか聞いたほうがいい。
ホテルはJSMが斡旋しているところだと安全だが、すぐ埋まるので早めにチェックする。飛行機も早く予約するほど安いので、参加が決まったらさっさと予約する。航空会社は英語に自信がないならANAやJALにすると日本⇔アメリカは日本人のクルーが乗っていたので割と安心だった。

出国審査や入国審査は、パスポートとESTAの準備をちゃんとしておけば割と安心できたが、これも複数人で同じ飛行機に乗れるとより安心。飛行機の待ち時間に暇を潰せる相手がいると助かるし、絡まれても多少は安心できる。

国際線の飛行機は、エコノミーは夜行バス、プレミアムエコノミーはちょっといい夜行バス、ビジネスはちっちゃいネカフェ、ファーストはネカフェっぽい印象を受けた。

今回、飛行機内での過ごし方は失敗してしまった。飛行機では、到着地の時間に合わせて過ごすべきだったが、出発地の時間で多くの時間を過ごしてしまったためか、時差ボケの影響が学会最終日まで残ってしまった。
体調万全で学会に参加したいなら、飛行機内で調整するか、少し早めに到着して睡眠調整できると良さそう。
どうせそんなに寝れないので、ずっと起きて仕事をするとかでもいいかもしれない。


### 食事について

米と生モノがほとんどないことを除くと、食べれるものがないという問題はなかった。ハンバーガーやピザ等を毎日食べてもいいという人は問題ないかもしれない。
ただ、物価が日本と比べて明らかに高く、1食安くても3000円くらいだった。予定はないが、本格的に住む場合は確実に自炊生活になりそう。スーパーに行ったら、果物は明らかに安く、バナナは1房で2ドルくらいなのに対し、クロワッサンは4個で7ドルだった。


### 英語について

観光地近辺は割と容赦して話してくれてたのでなんとかなったが、やはり話せるに越したことはない。アメリカに行き来するだけなら割と適当でも大丈夫だが、料理が1人分だけ来ないときとか、ちょっと聞きたいことがあるときに対処するにはある程度話せる必要はあるだろう。

英語については、学会参加者と研究関連の雑談できるくらいに話せると良いと感じた。自分は雑談できるほどには話せなかったために、もっと話せると他の参加者との交流も深まったと感じる場面が何度かあった。研究以外の部分で機会を逃すのはもったいないのを身をもって実感したので、英語を勉強するモチベーションが上がった。


## 総評

本当に行ってよかった。日本では数人しかやっていない分野の研究者が、JSMのような大きな学会ではそこそこの人数来ており、自分が今やっている研究にクリティカルな影響を与える研究にも出会える可能性も高い。新たな研究のアイデアを得る機会にもなるので、今後も積極的にこのような学会に参加したいという気持ちが高まった。

