---
title: "Curriculum Vitae"
author: "Keisuke Hanada"
date: "`r Sys.Date()`"  
output: 
  pdf_document:
    latex_engine: lualatex
mainfont: "Times New Roman"
geometry: "margin=1in"
fontsize: 12pt
---

## **Contact Information**  
- Name: Keisuke Hanada
- Address: Faculty of Medicine, Wakayama Medical University
- Email: khanada [at] wakayama-med.ac.jp
- ORCID: [0000-0002-1444-0280](https://orcid.org/0000-0002-1444-0280)
- GitHub: [https://github.com/keisuke-hanada](https://github.com/keisuke-hanada)
- Website: [https://keisuke-hanada.github.io/](https://keisuke-hanada.github.io/)

---

## Working Experience

- **2025/4 - Present**: Assistant Professor,  
  Faculty of Medicine, Wakayama Medical University
- **2024/4 - 2025/3**: Specially Appointed Assistant Professor,  
  Graduate School of Engineering Science, Osaka University
- **2019/4 - 2024/2**: Biostatistician,  
  Biometrics Department, Kyowa Kirin Co., Ltd

---

## Education

- **2020/4 - 2024/3**: Ph.D. in Data Science, Shiga University  
  Supervisor: Dr. Tomoyuki Sugimoto
- **2017/4 - 2019/3**: M.S. in the Graduate School of Science and Engineering, Kagoshima University  
  Supervisor: Dr. Tomoyuki Sugimoto
- **2013/4 - 2017/3**: B.Sc. Tech. in Faculty of Science and Technology, Hirosaki University  
  Supervisor: Dr. Kimitoshi Tsutaya


---


## Research Publications

### Peer-Reviewed Articles
1. Kojima, M., Orihara, S., \underline{Hanada, K}., & Ohigashi, T. (2026). Sample size re-estimation in blinded hybrid-control design using inverse probability weighting.  *Statistics in Medicine*, 45(3-5), e70429.
1. Kojima, M., Mano, H., Yamada, K., \underline{Hanada, K}., Tanaka, Y., & Moriya, J. (2025). Adjusting confidence intervals under covariate-adaptive randomization in non-inferiority and equivalence trials. *Contemporary Clinical Trials*, 158, 108099.
1. \underline{Hanada, K}., Moriya, J., & Kojima, M. (2024). Comparison of baseline covariate adjustment methods for restricted mean survival time. *Contemporary Clinical Trials*, 138, 107440.
1. \underline{Hanada, K}., & Sugimoto, T. (2024). Meta-Analysis for Time-to-event Outcome Based on Restored Individual Participant Data and Summary Statistics. *Japanese Journal of Biometrics*, 45(1), 115-131. (in Japanese)
1. \underline{Hanada, K}., & Sugimoto, T. (2023). Inference using an exact distribution of test statistic for random-effects meta-analysis. *Annals of the Institute of Statistical Mathematics*, 75(2), 281-302.

### Clinical researches
1. Hirano, S., \underline{Hanada, K}., & Maeda, H. (2025). Potential surrogate endpoint for B-cell hematologic malignancy: A systematic review and meta-analysis. *Scientific reports*, 19300.

### Preprints
1. \underline{Hanada, K}., & Sugimoto, T. (2025). Random-effects meta-analysis via generalized linear mixed models: A Bartlett-corrected approach for few studies. *arXiv preprint* arXiv:2508.08758.
1. \underline{Hanada, K}., & Sugimoto, T. (2024). Moment-based Random-effects Meta-analysis Equipped with Huber's M-Estimation. *arXiv preprint* arXiv:2407.04446.
1. \underline{Hanada, K}., & Kojima, M. (2024). Bayesian Parametric Methods for Deriving Distribution of Restricted Mean Survival Time. *arXiv preprint* arXiv:2406.06071.
1. \underline{Hanada, K}., & Kojima, M. (2024). Random Effect Restricted Mean Survival Time Model. *arXiv preprint* arXiv:2401.02048.


### Software and R Packages
1. rmstBayespara: Bayesian Restricted Mean Survival Time for Cluster Effect. R package. Available at: [https://cran.r-project.org/web/packages/rmstBayespara/](https://cran.r-project.org/web/packages/rmstBayespara/)
1. metaMest: meta-analysis by M-estimator based approach. R package. Available at: [https://github.com/keisuke-hanada/metaMest](https://github.com/keisuke-hanada/metaMest)

### Conference Presentations
1. \underline{Hanada, K}., & Sugimoto, T. (2025). Random-effects meta-analysis via generalized linear mixed models (GLMMs) for few studies, *The 13th Conference of the IASC-ARS*, Ho Chi Minh City.
1. \underline{Hanada, K}., & Kojima, M. (2025). Integrate Meta-analysis into Specific Study for Estimating Conditional Average Treatment Effect, *Joint Statistical Meeting 2025*, Nashville.
1. \underline{Hanada, K}., & Sugimoto, T. (2019). Non-Asymptotic Properties and Behaviors for Random-Effects Meta-Analysis When the Number of Studies Is Small, *The VI-th International Symposium on Biopharmaceutical Statistics*, Kyoto.


---


## Grants and Funding

- **2024/7 - 2026/3**: Japan Society for the Promotion of Science (JSPS), Grant-in-Aid for Research Activity Start-up [Principal Investigator]
- **2024/4 - 2027/3**: Japan Society for the Promotion of Science (JSPS), Grant-in-Aid for Scientific Research (C) [Co-Investigator]

---


## Awards
1. Best Presentation Award for Young Researcher (regular membership category), Annual meeting of The Biometric Society of Japan, 2025.


---

<!-- ## Teaching Experience

- **[Course Name]**, [Institution Name]  
  [Dates]  
  Number of Students: [Number of Students]  
  *[Brief description of the course and your role]*

--- -->

## Academic Service

- **Peer Review**  
  Japanese Journal of Statistics and Data Science
  Journal of the Royal Statistical Society: Series C (Applied Statistics)
  Journal of the Japan Statistical Society, Japanese Issue


<!-- - **Conference Organization**  
  [Conference Name], [Role], [Year] -->

---

<!-- ## Professional Memberships

- [Association Name], [Position (if applicable)], [Years]
- [Association Name], [Position (if applicable)], [Years]

---

## Skills

- **Statistical Software**: R, Python, SAS, STATA, [Other relevant software]  
- **Programming Languages**: C++, SQL, [Other relevant languages]  
- **Other Skills**: Git, LaTeX, [Other relevant tools or skills]

---

## References

1. [Reference Name], [Position], [Institution]  
   Email: [Email Address], Phone: [Phone Number]

2. [Reference Name], [Position], [Institution]  
   Email: [Email Address], Phone: [Phone Number] -->



<!-- ## Research Publications (in Japanese)

### 原著論文
1. \underline{花田圭佑}, & 杉本知之. (2024). イベント時間アウトカムに対する個人データ復元と要約統計量に基づくメタアナリシスとその性能. *計量生物学*, 45(1), 115-131.


### 学会発表
1. \underline{花田圭佑}, & 小島将裕. (2024). Random Effect Restricted Mean Survival Time Model, 2024年度統計関連学会連合大会.
1. \underline{花田圭佑}, & 杉本知之. (2024). 少数試験メタアナリシスでの分散推定, 日本計算機統計学会第38回大会.
1. \underline{花田圭佑}. (2023). イベント時間アウトカムの個人データ復元とメタアナリシス, 第5回かごしまデータ科学シンポジウム.
1. \underline{花田圭佑}, 小島将裕, & 守屋順之. (2023). 制限付き平均生存時間 (RMST) の共変量調整法の比較, 2023年度統計関連学会連合大会.
1. \underline{花田圭佑}. (2022). イベント数が少ないもとでの二値メタアナリシスの推測, 第3回かごしまデータ科学シンポジウム.
1. \underline{花田圭佑}, & 杉本知之. (2019). 試験数が少ない場合のランダム効果メタアナリシスの非漸近的性質, 日本計算機統計学会第33回シンポジウム.
1. \underline{花田圭佑}, & 杉本知之. (2018). ランダム効果DL層別解析における標本分布, 日本計算機統計学会第32回シンポジウム.
1. \underline{花田圭佑}, & 杉本知之. (2018). 正規母集団におけるランダム効果層別解析における標本分布, 大分統計談話会第57回大会.

---
-->
